### PR TITLE
Add Cults & Cosmic, fix KissKissBankBank spelling

### PR DESCRIPTION
**Pull request by sunny**
\o/

### CODE REVIEW

**Comment by tgautier** [comment]
Ok for me.

@cveneziani do we need a rebase & squash? (5 commits seems like a lot :grin:)

**Comment by cveneziani** [comment]
Yeah we definitely need a squash :grimacing:

**Comment by tgautier** [comment]
@sunny can you can squash all your commits into a meaningful one so we can merge?

**Comment by sunny** [comment]
With pleasure! I squashed it into two meaningful commits (spelling in one, additions in another).

**Comment by cveneziani** [comment]
:+1:

**Comment by sunny** [comment]
Merci !

**Comment by tgautier** [comment]
Mais de rien ! Merci à toi pour la PR :wink:

**Pull request merged**
