### PR TITLE
Added iMenlo agency

### PR DESCRIPTION
**Pull request by Sylvain**
Hi, 

I added my agency, iMenlo.

Thanks for the list!

Kind regards,

Sylvain

### CODE REVIEW

**Comment by flexbox** [comment]
Hello @Sylvain 
🚀 
feel free to meet us http://ruby-nord.org/

**Comment by cveneziani** [comment]
Guys, it's a comma separated value (CSV), not a comma-space separated value :wink: 
Fixed with https://github.com/ruby-nord/rubyshops/commit/d977d601a745a239573140821af7bcbdf6dc417c

**Comment by Sylvain** [comment]
Sorry, I thought to have been careful with that. Thanks for your change @cveneziani!

**Comment by cveneziani** [comment]
Not a big deal. You're welcome :smiley:

**Pull request merged**
